#H2 database configuration
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: lao
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true #show SQL
#    open-in-view: false