#H2 database configuration
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: lao
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true #show SQL



#    #H2 database configuration
#    spring.h2.console.enabled=true
#    spring.h2.console.path=/h2-console
#    spring.datasource.url=jdbc:h2:mem:testdb
#    spring.datasource.driverClassName=org.h2.Driver
#    spring.datasource.username=lao
#    spring.datasource.password=password
#    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#    #show SQL
#    spring.jpa.show-sql=true
