#H2 database configuration
spring:
  profiles:
    active: local
  jackson:
    serialization:
      indent_output: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Books
