openapi: 3.0.3
info:
  title: "E-Hymnal API"
  description: E-Hymnal
  version: 1.0.0

tags:
  - name: Add Hymn
    description: Add file and metadata of a hymn in the database
  - name: Update Hymn
    description: Update file and metadata of a hymn in the database
  - name: Delete Hymn
    description: Remove file and metadata of a hymn in the database
  - name: Display all Hymns
    description: Display all the hymns in the repository


paths:
  /add-file:
    post:
      tags:
        - Add Hymn
      summary: "Adding file and metadata of a hymn"
      description: ""
      operationId: addHymn
      requestBody:
        description: "Hymn object that needs to be added to the database"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hymn"
      responses:
        201:
          description: "Accepted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Accepted"

        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        403:
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalError"

  /update-file:
    post:
      tags:
        - Update Hymn
      summary: "Updating file and metadata of a hymn"
      description: ""
      operationId: updateHymn
      requestBody:
        description: "Hymn object that needs to be updated to the database"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Hymn"
      responses:
        201:
          description: "Accepted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Accepted"

        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        403:
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalError"

  /delete/{fileId}:
    delete:
      tags:
        - Delete Hymn
      summary: "Removing hymn file in the database"
      description: ""
      operationId: deleteHymn
      parameters:
        - in: path
          name: fileId
          schema:
            type: string
          required: true
          description: "File ID of the hymn file to  be deleted."
          example: "001"
      responses:
        201:
          description: "Accepted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Accepted"

        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        403:
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalError"

  /hymns:
    get:
      tags:
        - Display all Hymns
      summary: "Displaying all hymns in the database"
      description: ""
      operationId: getAllHymn
      responses:
        201:
          description: "Accepted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Accepted"

        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
        403:
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Forbidden"
        500:
          description: "Internal Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalError"

components:
  schemas:
    Hymn:
      type: object
      properties:
        id:
          type: string
          example: "001"
        hymnNumber:
          type: integer
          format: int64
          example: 100
        hymnTitle:
          type: string
          example: "Sample Hymn Title"
        hymnFile:
          type: string
          format: base64
          example: someBase64EncodedHymn


    Accepted:
      type: object
      properties:
        code:
          type: integer
          default: 200
        description:
          type: string
          default: "Request Accepted."

    BadRequest:
      type: object
      properties:
        code:
          type: integer
          default: 400
        description:
          type: string
          default: "Bad Request."

    Forbidden:
      type: object
      properties:
        code:
          type: integer
          default: 403
        description:
          type: string
          default: "Forbidden Access."

    InternalError:
      type: object
      properties:
        code:
          type: integer
          default: 500
        description:
          type: string
          default: "Internal Error"
